services:
  # Node.js Service
  nodejs:
    container_name: youtube-share-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "84:84"
      - "85:85"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    depends_on:
      - mongodb
  
  # MongoDB Service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27018"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
